


GET http://localhost:3004/kanye


###


GET http://localhost:3004/


###

POST http://localhost:3004/kanye
Content-Type: application/json

{
    "quote": "Three may keep a secret if two of them are dead"
    
}

###

GET http://localhost:3004/quotes

###


GET http://localhost:3004/quotes/94f83cb4-7bc7-4192-979b-c2cfb962a47d


####


DELETE http://localhost:3004/quotes/788dbdd4-b8fe-4575-ba7c-72f34e86429a
